import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isWeb = Platform.OS === 'web';

const COLORS = {
  primary: '#7C3AED',
  primaryLight: '#EDE9FE',
  background: '#F8F9FF',
  surface: 'rgba(255,255,255,0.92)',
  text: '#1A1035',
  textLight: '#6B7280',
  border: 'rgba(167,139,250,0.30)',
  borderActive: '#7C3AED',
  white: '#FFFFFF',
  danger: '#DC2626',
  success: '#16A34A',
};

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: isWeb ? 0 : 20,
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  card: {
    width: isWeb ? 760 : '100%',
    maxWidth: 860,
    backgroundColor: COLORS.surface,
    borderRadius: 28,
    padding: isWeb ? 36 : 22,
    marginTop: isWeb ? 32 : 18,
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.12)',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.09,
    shadowRadius: 28,
    elevation: 6,
  },
  header: {
    marginBottom: 22,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginBottom: 18,
  },
  backText: {
    marginLeft: 6,
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primary,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: COLORS.text,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    lineHeight: 20,
    maxWidth: 700,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6D28D9',
    marginBottom: 14,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  fieldGroup: {
    marginBottom: 22,
  },
  formRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  inputGroup: {
    flex: 1,
    minWidth: 140,
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 8,
  },
  inputWrapper: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 52,
  },
  inputWrapperActive: {
    borderColor: COLORS.borderActive,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  input: {
    fontSize: 15,
    color: COLORS.text,
    minHeight: 40,
    padding: 0,
  },
  pickerWrapper: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: 52,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  picker: {
    width: '100%',
    height: 52,
    color: COLORS.text,
  },
  pickerItem: {
    color: COLORS.text,
    fontSize: 15,
  },
  radioRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  radioOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  radioOptionActive: {
    borderColor: COLORS.primary,
    backgroundColor: '#F3E8FF',
  },
  radioLabel: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '600',
  },
  helperText: {
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 4,
  },
  errorBox: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
    marginBottom: 16,
  },
  errorText: {
    color: '#991B1B',
    fontSize: 13,
    fontWeight: '600',
  },
  submitWrapper: {
    marginTop: 10,
  },
  note: {
    fontSize: 13,
    color: COLORS.textLight,
    marginTop: 2,
  },
  childProfileBox: {
    marginBottom: 18,
    padding: 18,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.14)',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 5,
  },
  profileCard: {
    borderRadius: 20,
    padding: 18,
    backgroundColor: '#F8F7FF',
  },
  profileHeaderBlock: {
    marginBottom: 14,
  },
  profileName: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.text,
    marginBottom: 4,
  },
  profileMeta: {
    fontSize: 13,
    color: COLORS.textLight,
  },
  profileDetailsRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  profileDetail: {
    flex: 1,
    minWidth: 140,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.12)',
  },
  profileLabel: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 6,
    fontWeight: '700',
  },
  profileValue: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '700',
  },
  inviteActionButton: {
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#7C3AED',
    alignItems: 'center',
  },
  inviteActionText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  inviteBox: {
    marginTop: 14,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.12)',
  },
  inviteLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 10,
  },
  inviteInput: {
    borderColor: 'rgba(124,58,237,0.14)',
    marginBottom: 12,
  },
  inviteSubmitButton: {
    backgroundColor: '#4C1D95',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
  },
  inviteSubmitText: {
    color: '#fff',
    fontWeight: '800',
  },
  successText: {
    color: '#16A34A',
    marginTop: 10,
    fontSize: 13,
    fontWeight: '600',
  },

  // ✅ Styles pour l'écran de succès
  successContainer: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 20,
  },
  inviteButtonContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 30,
  },
  inviteButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  inviteButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  inviteStatusText: {
    color: COLORS.success,
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  inviteButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 12,
  },
  inviteCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.primary,
    alignItems: 'center',
  },
  inviteCancelText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  successMessage: {
    alignItems: 'center',
    marginBottom: 40,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.text,
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  successSubtitle: {
    fontSize: 16,
    color: COLORS.textLight,
    textAlign: 'center',
    lineHeight: 22,
  },
  childProfileCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    padding: 24,
    marginBottom: 40,
    width: isWeb ? 400 : width * 0.9,
    maxWidth: 400,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  childAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  childInitials: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.white,
  },
  childInfo: {
    flex: 1,
  },
  childName: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 4,
  },
  childDetails: {
    fontSize: 14,
    color: COLORS.textLight,
    marginBottom: 4,
  },
  childCognitif: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '600',
  },
  backToFormButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
  },
  backToFormText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },

  // Modal d'invitation
  inviteModal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  inviteModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 24,
    width: isWeb ? 400 : width * 0.9,
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  inviteModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  inviteModalSubtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    marginBottom: 20,
    textAlign: 'center',
  },
  inviteInput: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 16,
    backgroundColor: COLORS.background,
  },
  inviteError: {
    color: COLORS.danger,
    fontSize: 14,
    marginBottom: 16,
    textAlign: 'center',
  },
  inviteSuccess: {
    color: COLORS.success,
    fontSize: 14,
    marginBottom: 16,
    textAlign: 'center',
  },
  inviteStatusText: {
    color: COLORS.success,
    fontSize: 14,
    marginTop: 12,
    textAlign: 'center',
  },
  inviteButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inviteCancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    marginRight: 8,
  },
  inviteCancelText: {
    color: COLORS.textLight,
    fontSize: 16,
    fontWeight: '600',
  },
  inviteSendButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    marginLeft: 8,
  },
  inviteSendButtonDisabled: {
    opacity: 0.6,
  },
  inviteSendText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
  },
});
