import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isWeb = Platform.OS === 'web';

const COLORS = {
  primary: '#7C3AED',
  primaryLight: '#EDE9FE',
  background: '#F8F9FF',
  surface: 'rgba(255,255,255,0.92)',
  text: '#1A1035',
  textLight: '#6B7280',
  border: 'rgba(167,139,250,0.30)',
  borderActive: '#7C3AED',
  white: '#FFFFFF',
  danger: '#DC2626',
  success: '#16A34A',
};

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: isWeb ? 0 : 20,
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  card: {
    width: isWeb ? 760 : '100%',
    maxWidth: 860,
    backgroundColor: COLORS.surface,
    borderRadius: 28,
    padding: isWeb ? 36 : 22,
    marginTop: isWeb ? 32 : 18,
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.12)',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.09,
    shadowRadius: 28,
    elevation: 6,
  },
  header: {
    marginBottom: 22,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginBottom: 18,
  },
  backText: {
    marginLeft: 6,
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primary,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: COLORS.text,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    lineHeight: 20,
    maxWidth: 700,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6D28D9',
    marginBottom: 14,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  fieldGroup: {
    marginBottom: 22,
  },
  formRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  inputGroup: {
    flex: 1,
    minWidth: 140,
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 8,
  },
  inputWrapper: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 52,
  },
  inputWrapperActive: {
    borderColor: COLORS.borderActive,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  input: {
    fontSize: 15,
    color: COLORS.text,
    minHeight: 40,
    padding: 0,
  },
  pickerWrapper: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: 52,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  picker: {
    width: '100%',
    height: 52,
    color: COLORS.text,
  },
  pickerItem: {
    color: COLORS.text,
    fontSize: 15,
  },
  radioRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  radioOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  radioOptionActive: {
    borderColor: COLORS.primary,
    backgroundColor: '#F3E8FF',
  },
  radioLabel: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '600',
  },
  helperText: {
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 4,
  },
  errorBox: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
    marginBottom: 16,
  },
  errorText: {
    color: '#991B1B',
    fontSize: 13,
    fontWeight: '600',
  },
  successBox: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#DCFCE7',
    borderWidth: 1,
    borderColor: '#86EFAC',
    marginBottom: 16,
  },
  successText: {
    color: '#166534',
    fontSize: 13,
    fontWeight: '600',
  },
  submitWrapper: {
    marginTop: 10,
  },
  note: {
    fontSize: 13,
    color: COLORS.textLight,
    marginTop: 2,
  },
  childProfileBox: {
    marginBottom: 18,
    padding: 18,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.14)',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 5,
  },
  profileCard: {
    borderRadius: 20,
    padding: 18,
    backgroundColor: '#F8F7FF',
  },
  profileHeaderBlock: {
    marginBottom: 14,
  },
  profileName: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.text,
    marginBottom: 4,
  },
  profileMeta: {
    fontSize: 13,
    color: COLORS.textLight,
  },
  profileDetailsRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  profileDetail: {
    flex: 1,
    minWidth: 140,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(124,58,237,0.12)',
  },
  profileLabel: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 6,
    fontWeight: '700',
  },
  profileValue: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '700',
  },
  actionsWrapper: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonSecondary: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
  },
  actionButtonSecondaryText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingText: {
    fontSize: 16,
    color: COLORS.text,
    marginTop: 16,
  },
});
